const keys = {
  PERMISSION_GRANT_REQUESTED: "PERMISSION_GRANT_REQUESTED",
  ONBOARDING_COMPLETED: "ONBOARDING_COMPLETED",
  FAVORITE_TAG_IDS: "FAVORITE_TAG_IDS",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  SHOULD_LOGIN: "SHOULD_LOGIN",
};

export default keys;
