const keys = {
  PERMISSION_GRANT_REQUESTED: "PERMISSION_GRANT_REQUESTED",
  ONBOARDING_COMPLETED: "ONBOARDING_COMPLETED",
  INTEREST_TAG_IDS: "INTEREST_TAG_IDS",
  REFRESH_TOKEN: "REFRESH_TOKEN",
};

export default keys;
